// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbrmrcscxpjyhirsugao.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdicm1yY3NjeHBqeWhpcnN1Z2FvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzODU4MDEsImV4cCI6MjA2OTk2MTgwMX0.OPMpk-U5IArScyO6-SogdbJXdDSX-2ln-obTwdJHCgw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});